import mongoose from "mongoose";

const ProductSchema = new mongoose.Schema(
	{
		Client: String,
		ProductName: String,
		Category: String,
		Url: String,
		ISBN: String,
		ISSN: String,
		PublicationType: String,
		FirstYearPublished: String,
		DOI: String,
		Description: String,
		IssuesPerYear: String,
		PublicationFormats: String,
		OnlineContentFrequency: String,
		TopicsCovered: String,
		Uniqueness: String,
		AverageNumberYearly: String,
		DigitalArchive: String,
		DigitalArchiveDate: String,
		ArchiveCount: String,
		Publisher: String,
		StaffDescription: String,
		EditorName: String,
		MarquisEditor: String,
		Freelancers: String,
		OwnFreelancerContent: String,
		OriginalVideoMedia: String,
		VideoMediaRights: String,
		OriginalPhotoMedia: String,
		PhotoMediaRights: String,
		OriginalGraphs: String,
		GraphsRights: String,
		AudienceDescription: String,
		Circulation: String,
		AnnualTraffic: String,
		SubscriptionType: String,
		AnnualSubPrice: String,
		IndividualCopyPrice: String,
		NumberOfEvents: String,
		EventOne: String,
		EventOneDescription: String,
		EventOneRecording: String,
		EventTwo: String,
		EventTwoDescription: String,
		EventTwoRecording: String,
		EventThree: String,
		EventThreeDescription: String,
		EventThreeRecording: String,
		NumberOfNewsletters: String,
		NewsletterOne: String,
		NewsletterOneFormat: String,
		NewsletterOneDescription: String,
		NewsletterOneFrequency: String,
		NewletterOneUniqueness: String,
		NewsletterTwo: String,
		NewsletterTwoFormat: String,
		NewsletterTwoDescription: String,
		NewsletterTwoFrequency: String,
		NewletterTwoUniqueness: String,
		NewsletterThree: String,
		NewsletterThreeFormat: String,
		NewsletterThreeDescription: String,
		NewsletterThreeFrequency: String,
		NewletterThreeUniqueness: String,
		ReportsResearch: String,
		NumberOfReports: String,
		ReportResearchDescription: String,
		CompetitivePosition: String,
		Competitor: String,
		RetailPrice: String,
	},
	{ timestamps: true }
);

const Product = mongoose.model("Product", ProductSchema);
export default Product;

// above is a schema passed into mongoose that allows mongoose to make sure all data you pass into database has to follow this structure(schema)
